// <auto-generated />
namespace MuseCommerce.Data.Repositories.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class updatepermission : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatepermission));
        
        string IMigrationMetadata.Id
        {
            get { return "201606150846080_updatepermission"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
